apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  annotations:
    # This annotation tells the cloud provider to assign an external IP address
    # to the service.
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 443
      targetPort: 8080
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: argocd-server
